### PR TITLE
[ADD] Protocol support for Magento2

### PR DESCRIPTION
**Pull request by StefanRijnhart**
This branch adds minimal protocol support for the Magento2 REST API. The reason I am adding only this is because it is what is needed to bring Magento2 support to https://github.com/oca/connector-magento.

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
@tarunbhardwaj it would be good to tell me if you are willing to take this change or not. Could you do that?

**Comment by StefanRijnhart** [comment]
ping @sharoonthomas

**Comment by sharoonthomas** [comment]
LGTM. I would squash and merge with all the commits

**Comment by StefanRijnhart** [comment]
Thanks for your response. Now squashed into a single commit.

**Comment by StefanRijnhart** [comment]
Can you please accept or reject this, so that I can finish the upstream work?

**Comment by tarunbhardwaj** [comment]
@StefanRijnhart license of this contribution will be considered BSD.

**Comment by StefanRijnhart** [comment]
Thanks!

**Pull request merged**
