### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by aLoneStrider**
The metaclass definition line can be removed or left, Python3 ignores metaclass assignment other than class parameter

### CODE REVIEW

**Comment by ImreC** [comment]
@tarunbhardwaj could you merge this one? I had to manually update api.py on two machines because the scripts throw an error without this change. Cheers!

**Comment by sharoonthomas** [comment]
Would this work on py2 and 3?

**Comment by ImreC** [comment]
@sharoonthomas manually implementing this change will allow the package to work on py 3+. Crazy that this hasn't been merged in over 1.5 years.

**Comment by sharoonthomas** [comment]
fixed by #21

**Pull request closed without merging**
