### PR TITLE
Call with http method

### PR DESCRIPTION
**Pull request by StefanRijnhart**
This allows creating and updating records in Magento 2. Also adds support for storeview specific operations.

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
@tarunbhardwaj can you have a look?

**Comment by thomaspaulb** [comment]
@StefanRijnhart it seems that this needs rebasing, your PR is based on `2.2` and `3.0` is out now.

**Comment by StefanRijnhart** [comment]
@thomaspaulb Why rebase? I don't see any conflicts.

**Comment by StefanRijnhart** [comment]
Correction: will rebase to validate compatibility with Python 3. Thanks!

**Comment by StefanRijnhart** [comment]
Rebased, and still green!

**Comment by thomaspaulb** [comment]
I also didnt see any conflicts, but the 2.2 version didnt install for me
because of its dependency on suds. The 3.0 one depends on suds-jurko.
Anyway, I hope it will now be merged soon!

Op 10 nov. 2017 08:50 schreef "Stefan Rijnhart (Opener)" <
notifications@github.com>:

**Comment by sharoonthomas** [comment]
@StefanRijnhart is this something you are still using and should this be merged?

**Comment by StefanRijnhart** [comment]
Yes, absolutely! This allows us to push pickings, invoices and stock levels to Magento2.

**Comment by sharoonthomas** [comment]
great, @StefanRijnhart could you send this PR to develop branch instead? That's the development version and we can merge it there. This will then be merged into master on next release.

**Comment by StefanRijnhart** [comment]
Here you go: https://github.com/fulfilio/python-magento/pull/22

**Pull request closed without merging**
